---
redis_password: "IntraNet-Redis-2026!ChangeMe"
api_app_dir: /opt/mini-orch
loadtest_dir: /opt/mini-orch-loadtest
loadtest_service_name: mini-orch-loadtest
loadtest_env_file: /etc/mini-orch-loadtest.env
loadtest_port: 5001
loadtest_bind_host: ""
api_venv_path: /opt/mini-orch-venv
api_service_name: mini-orch-api
api_env_file: /etc/mini-orch-api.env
api_data_dir: /var/lib/mini-orch
sqlite_db_path: /var/lib/mini-orch/jobs.db
sqlite_backup_dir: /var/backups/mini-orch

queue_stream_key: jobs:stream

worker_binary_src: ../node2_worker/bin/mini-orch-worker
worker_binary_dest: /usr/bin/mini-orch-worker
worker_service_name: mini-orch-worker
worker_env_file: /etc/mini-orch-worker.env
worker_log_file: /var/log/mini-orch/worker.log
worker_queue_group: mini-orch-workers
worker_queue_batch_size: 10
worker_queue_block_ms: 5000
worker_status_retry_interval_ms: 30000

status_stream_key: jobs:status
status_failed_key: jobs:status:failed
status_consumer_service_name: mini-orch-status-consumer
status_consumer_group: status-updaters
status_consumer_block_ms: 5000