---

api_env_src: ../config/node1/mini-orch-api.env
api_env_dest: /etc/mini-orch-api.env
snmp_env_src: ../config/node1/mini-orch-snmp.env
snmp_env_dest: /etc/mini-orch-snmp.env
loadtest_env_src: ../config/node1/mini-orch-loadtest.env
loadtest_env_dest: /etc/mini-orch-loadtest.env
status_consumer_env_src: ../config/node1/mini-orch-status-consumer.env
status_consumer_env_dest: /etc/mini-orch-status-consumer.env
publish_failed_checker_env_src: ../config/node1/mini-orch-publish-failed-checker.env
publish_failed_checker_env_dest: /etc/mini-orch-publish-failed-checker.env
worker_env_src: ../config/node2/mini-orch-worker.env
worker_env_dest: /etc/mini-orch-worker.env

api_venv_path: /opt/mini-orch-venv
api_app_dir: /opt/mini-orch
loadtest_dir: /opt/mini-orch-loadtest

api_service_name: mini-orch-api
loadtest_service_name: mini-orch-loadtest
snmp_collector_service_name: mini-orch-snmp-collector
status_consumer_service_name: mini-orch-status-consumer

api_data_dir: /var/lib/mini-orch
sqlite_db_path: /var/lib/mini-orch/jobs.db
sqlite_backup_dir: /var/backups/mini-orch

api_log_file: /var/log/mini-orch/api.log
status_consumer_log_file: /var/log/mini-orch/status_consumer.log
snmp_collector_log_file: /var/log/mini-orch/snmp_collector.log
loadtest_log_file: /var/log/mini-orch/loadtest.log
publish_failed_checker_log_file: /var/log/mini-orch/publish_failed_checker.log

worker_binary_src: ../node2_worker/bin/mini-orch-worker
worker_binary_dest: /usr/bin/mini-orch-worker
worker_service_name: mini-orch-worker

worker_log_file: /var/log/mini-orch/worker.log

